package br.com.genovi.domain.enums;

public enum TypeRaca {
    MERINO,
    SUFFOLK,
    HAMPSHIRE,
    SOUTHDOWN,
    DORSET_HORN,
    CORRIEDALE,
    ROMNEY,
    LEICESTER,
    TEXEL,
    CHAROLLAIS,
    CHEVIOT,
    JACOB,
    BRAZILIAN_SOMALI,
    DORPER,
    ASSAF,
    AWASSI,
    BLACKHEAD_PERSIAN,
    VALAIS_BLACKNOSE,
    SHETLAND,
    NORTH_COUNTRY_CHEVIOT,
    BORDER_LEICESTER,
    CALIFORNIA_RED,
    COTSWOLD,
    KARAKUL,
    CASTLEMILK_MOORIT,
    HILL_RADNOR,
    FINNSHEEP;
}

